#!/bin/sh

# Copyright 2020, cPanel, L.L.C.
# All rights reserved.
# http://cpanel.net
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the owner nor the names of its contributors may be
# used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ORIG_BASE=$1
ORIG_REMOTE=$2
ORIG_LOCAL=$3
ORIG_MERGED=$4
GIT_MERGETOOL_GUI=${5:-false}
TOOL_MODE=${6:-merge}

# The convert() and unconvert() functions can be changed, while everything else
# remains the same, for other file formats.
convert() {
	sqlite3 "$1" .dump > "$2"
}
unconvert() {
	rm -f -- "$2"
	sqlite3 "$2" ".read '$1'"
}

# Determine correct mergetool to run.
. "$(git --exec-path)/git-mergetool--lib"
printf "Using mergetool: %s\n" "${MERGETOOL:=$(get_merge_tool)}"

# If set before get_merge_tool is run, errors occur.
set -e

# Ensure no temporary files are left behind.
CLEANUP=()
cleanup() { rm -f -- "${CLEANUP[@]}"; }
trap 'cleanup' EXIT

# Convert files to text.
text_filename() { mktemp -p "$(dirname "$1")" "$(basename "$1").XXXXXX" --suffix=.text; }
if [ -n "$ORIG_BASE" ];   then BASE=$(text_filename "$ORIG_BASE")    ; CLEANUP+=( "$BASE" )  ; convert "$ORIG_BASE"   "$BASE";   fi
if [ -n "$ORIG_REMOTE" ]; then REMOTE=$(text_filename "$ORIG_REMOTE"); CLEANUP+=( "$REMOTE" ); convert "$ORIG_REMOTE" "$REMOTE"; fi
if [ -n "$ORIG_LOCAL" ];  then LOCAL=$(text_filename "$ORIG_LOCAL")  ; CLEANUP+=( "$LOCAL" ) ; convert "$ORIG_LOCAL"  "$LOCAL";  fi
if [ -n "$ORIG_MERGED" ]; then MERGED=$(text_filename "$ORIG_MERGED"); CLEANUP+=( "$MERGED" ); convert "$ORIG_MERGED" "$MERGED"; fi

run_merge_tool "$MERGETOOL" "$( test -n "$BASE" && printf true || printf false )"

# Reverse the conversion for the final result if $ORIG_MERGED is passed in.  If
# not, this is likely diff mode and we can ignore the file.
[ -z "$ORIG_MERGED" ] || unconvert "$MERGED" "$ORIG_MERGED"
